name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
    paths: # Optional: Only run if files in 'docs' change
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Use the same Node.js version you use locally
        cache: 'npm'
        cache-dependency-path: docs/package-lock.json

    - name: Install dependencies
      run: npm install
      working-directory: ./docs

    - name: Build website
      run: npm run build
      working-directory: ./docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build # Deploy the contents of the build directory
        #  cname: example.com  # If you're using a custom domain